[package]
name = "ore_jdwp"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
futures-util = "0.3.31"
tokio = { version = "1.47.1", features = ["full", "rt-multi-thread"] }
